query GetComments(
  	$page_id: String!,
    $after: String,
  	$max_comments_at_toplevel: Int = 5,
  	$max_comments_per_sublevel: Int = 10
) {
    comments(page: $page_id, first: $max_comments_at_toplevel, after: $after) {
        ...commentConnectionFields
        edges { node { children(first: $max_comments_per_sublevel) {
            ...threeLevelsOfChildComments
        } } }
    }
}

query LoadMoreChildComments(
    $commentID: ID!,
    $after: String,
  	$max_comments_per_sublevel: Int = 10
) {
    comment(id: $commentID) {
        children(first: $max_comments_per_sublevel, after: $after) {
            ...threeLevelsOfChildComments
        }
    }
}

fragment threeLevelsOfChildComments on CommentGQLNodeConnection {
    ...commentConnectionFields
    edges { node {
        children(first: $max_comments_per_sublevel) {
            ...commentConnectionFields
            edges { node {
                # Three levels shown by default is enough, amirite
                children(first: 0) {
                    ...commentConnectionFields
                }
            } }
        }
    } }
}

fragment commentConnectionFields on CommentGQLNodeConnection {
    edges {
        node {
        ...commentFields
        }
    }
    pageInfo {
        endCursor
        hasNextPage
    }
}

fragment commentFields on CommentGQLNode {
    id
    dateCreated
    dateEdited
    author {
        username
    }
    text
}
